site_name: WordPress Docker
theme: null
theme_dir: readthedocs
repo_url: https://github.com/etopian/wordpressdocker
edit_uri: edit/master/docs/
google_analytics: ['UA-63062106-4', 'www.wordpressdocker.com']
site_url: http://www.wordpressdocker.com